name: Sync Releases from Original Repository

on:
  schedule:
    - cron: "0 * * * *"  # 每小时同步一次（UTC 时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq  # 安装 jq 工具

      - name: Fetch Original Repository Releases
        id: fetch_releases
        run: |
          ORIGINAL_REPO="blinko-space/blinko"  # 替换为原仓库的 owner/repo
          GH_TOKEN=${{ secrets.GH_TOKEN }}
          RELEASES=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$ORIGINAL_REPO/releases?per_page=3" \
            | jq '.[] | {id: .id, tag_name: .tag_name, name: .name}')
          
          # 检查 curl 请求是否成功
          if [ -z "$RELEASES" ]; then
            echo "Failed to fetch releases from $ORIGINAL_REPO"
            exit 1
          fi
          
          # 完整输出 RELEASES 的内容
          echo "RELEASES: $RELEASES"
          
          # 检查 RELEASES 是否为空
          if [ "$(echo "$RELEASES" | jq '. | length')" -eq 0 ]; then
            echo "No releases found in $ORIGINAL_REPO"
            exit 0
          fi
          
          echo "::set-output name=releases::$RELEASES"

      - name: Create Releases in Fork Repository
        run: |
          GH_TOKEN=${{ secrets.GH_TOKEN }}
          RELEASES=${{ steps.fetch_releases.outputs.releases }}
          for release in $(echo "$RELEASES" | jq -c '.'); do
            TAG_NAME=$(echo "$release" | jq -r '.tag_name')
            NAME=$(echo "$release" | jq -r '.name')
            BODY="release $NAME, $TAG_NAME"
            echo "Processing Release: $TAG_NAME - $NAME"

            # 创建 Release
            curl -X POST -H "Authorization: token $GH_TOKEN" \
              -d "{\"tag_name\":\"$TAG_NAME\",\"name\":\"$NAME\",\"body\":$ESCAPED_BODY,\"draft\":false,\"prerelease\":false}" \
              "https://api.github.com/repos/LiangWei88/blinko/releases"
          done