name: Sync Fork Repository and Releases

on:
  schedule:
    - cron: "0 * * * *"  # 每小时同步一次（UTC 时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3

      - name: Add Original Repository as Remote
        run: |
          git remote add upstream https://github.com/blinko-space/blinko.git  # 替换为原仓库的 URL
          git fetch upstream

      - name: Sync with Original Repository
        run: |
          git fetch upstream
          git checkout main  # 替换为原仓库的主分支名称
          git rebase upstream/main
          git push origin main

  sync-releases:
    runs-on: ubuntu-latest
    needs: sync-fork  # 等待代码同步完成后再同步 Release

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3

      - name: Fetch Original Repository Releases
        id: fetch_releases
        run: |
          ORIGINAL_REPO="blinko-space/blinko"  # 替换为原仓库的 owner/repo
          GH_TOKEN=${{ secrets.GH_TOKEN }}
          RELEASES=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$ORIGINAL_REPO/releases")
          echo "::set-output name=releases::$RELEASES"

      - name: Create Releases in Fork Repository
        run: |
          GH_TOKEN=${{ secrets.GH_TOKEN }}
          RELEASES=${{ steps.fetch_releases.outputs.releases }}
          for release in $(echo "$RELEASES" | jq -c '.[]'); do
            TAG_NAME=$(echo "$release" | jq -r '.tag_name')
            NAME=$(echo "$release" | jq -r '.name')
            BODY=$(echo "$release" | jq -r '.body')
            curl -X POST -H "Authorization: token $GH_TOKEN" \
              -d "{\"tag_name\":\"$TAG_NAME\",\"name\":\"$NAME\",\"body\":\"$BODY\",\"draft\":false,\"prerelease\":false}" \
              "https://api.github.com/repos/LiangWei88/blinko/releases"  # 替换为你的 Fork 仓库的 owner/repo
          done